server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

#注册微服务到Eureka Server
eureka:
  client:
    service-url:
      #      defaultZone: http://localhost:7001/eureka # 单机
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #集群
  instance:
    instance-id: gateway-9527.com #修改Eureka控制台集成实例的status
    prefer-ip-address: true  # 浮于status连接时 访问路径显示ip

info:  #信息完善
  app.name: rc-microservicecloud
  company.name: www.baidu.com
#  build.version: ${project.version}$  # delimiter 不知道如何去设置


## 配置路由规则
#共有三种方式进行访问
#1.http://localhost:8001/dept/1
#2.http://myzuul.com:9527/microservicecloud-dept/dept/1
#3.http://myzuul.com:9527/mydept/dept/1
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept  # 映射规则
    mydept.path: /mydept/**
#  ignored-services: microservicecloud-dept # 禁用http://myzuul.com:9527/microservicecloud-dept/dept/1
  ignored-services: '*'     #禁用所有真实服务名称
  prefix: /rc

